# Generated by Django 4.2.6 on 2024-02-13 12:39

from django.db import migrations
from phonenumber_field.modelfields import PhoneNumberField


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_num',
            field=PhoneNumberField(max_length=128, region=None),
        ),
    ]
